// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct AttributeCertificateVersion1_2009_AttributeCertificateInfoV1: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: AttributeCertificateVersion1_2009_AttCertVersionV1?
    @usableFromInline var subject: AttributeCertificateVersion1_2009_AttributeCertificateInfoV1_subject_Choice
    @usableFromInline var issuer: PKIX1Implicit88_GeneralNames
    @usableFromInline var signature: AuthenticationFramework_AlgorithmIdentifier
    @usableFromInline var serialNumber: ArraySlice<UInt8>
    @usableFromInline var attCertValidityPeriod: AuthenticationFramework_AttCertValidityPeriod
    @usableFromInline var attributes: [PKIX_CommonTypes_2009_AttributeSet]
    @usableFromInline var issuerUniqueID: SelectedAttributeTypes_UniqueIdentifier?
    @usableFromInline var extensions: AuthenticationFramework_Extensions?
    @inlinable init(version: AttributeCertificateVersion1_2009_AttCertVersionV1?, subject: AttributeCertificateVersion1_2009_AttributeCertificateInfoV1_subject_Choice, issuer: PKIX1Implicit88_GeneralNames, signature: AuthenticationFramework_AlgorithmIdentifier, serialNumber: ArraySlice<UInt8>, attCertValidityPeriod: AuthenticationFramework_AttCertValidityPeriod, attributes: [PKIX_CommonTypes_2009_AttributeSet], issuerUniqueID: SelectedAttributeTypes_UniqueIdentifier?, extensions: AuthenticationFramework_Extensions?) {
        self.version = version
        self.subject = subject
        self.issuer = issuer
        self.signature = signature
        self.serialNumber = serialNumber
        self.attCertValidityPeriod = attCertValidityPeriod
        self.attributes = attributes
        self.issuerUniqueID = issuerUniqueID
        self.extensions = extensions

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            var version: AttributeCertificateVersion1_2009_AttCertVersionV1? = nil
var peek_version = nodes
if let next = peek_version.next(), next.identifier == AttributeCertificateVersion1_2009_AttCertVersionV1.defaultIdentifier {
    version = try AttributeCertificateVersion1_2009_AttCertVersionV1(derEncoded: &nodes)
}
            let subject: AttributeCertificateVersion1_2009_AttributeCertificateInfoV1_subject_Choice = try AttributeCertificateVersion1_2009_AttributeCertificateInfoV1_subject_Choice(derEncoded: &nodes)
            let issuer: PKIX1Implicit88_GeneralNames = try PKIX1Implicit88_GeneralNames(derEncoded: &nodes)
            let signature: AuthenticationFramework_AlgorithmIdentifier = try AuthenticationFramework_AlgorithmIdentifier(derEncoded: &nodes)
            let serialNumber: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let attCertValidityPeriod: AuthenticationFramework_AttCertValidityPeriod = try AuthenticationFramework_AttCertValidityPeriod(derEncoded: &nodes)
            let attributes: [PKIX_CommonTypes_2009_AttributeSet] = try DER.sequence(of: PKIX_CommonTypes_2009_AttributeSet.self, identifier: .sequence, nodes: &nodes)
            var issuerUniqueID: SelectedAttributeTypes_UniqueIdentifier? = nil
var peek_issuerUniqueID = nodes
if let next = peek_issuerUniqueID.next(), next.identifier == SelectedAttributeTypes_UniqueIdentifier.defaultIdentifier {
    issuerUniqueID = try SelectedAttributeTypes_UniqueIdentifier(derEncoded: &nodes)
}
            var extensions: AuthenticationFramework_Extensions? = nil
var peek_extensions = nodes
if let next = peek_extensions.next(), next.identifier == AuthenticationFramework_Extensions.defaultIdentifier {
    extensions = try AuthenticationFramework_Extensions(derEncoded: &nodes)
}

            return AttributeCertificateVersion1_2009_AttributeCertificateInfoV1(version: version, subject: subject, issuer: issuer, signature: signature, serialNumber: serialNumber, attCertValidityPeriod: attCertValidityPeriod, attributes: attributes, issuerUniqueID: issuerUniqueID, extensions: extensions)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            if let version = self.version { try coder.serialize(version) }
            try coder.serialize(subject)
            try coder.serialize(issuer)
            try coder.serialize(signature)
            try coder.serialize(serialNumber)
            try coder.serialize(attCertValidityPeriod)
            try coder.serializeSequenceOf(attributes)
            if let issuerUniqueID = self.issuerUniqueID { try coder.serialize(issuerUniqueID) }
            if let extensions = self.extensions { try coder.serialize(extensions) }

        }
    }
}
