// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias AttributeCertificateVersion1_2009_AlgorithmIdentifier = AuthenticationFramework_AlgorithmIdentifier
