// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct CHAT_FileOffer: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var id: ASN1OctetString
    @usableFromInline var name: ASN1OctetString
    @usableFromInline var size: ArraySlice<UInt8>
    @usableFromInline var mime: ASN1OctetString
    @usableFromInline var hash: ASN1OctetString?
    @usableFromInline var chunks: ArraySlice<UInt8>
    @inlinable init(id: ASN1OctetString, name: ASN1OctetString, size: ArraySlice<UInt8>, mime: ASN1OctetString, hash: ASN1OctetString?, chunks: ArraySlice<UInt8>) {
        self.id = id
        self.name = name
        self.size = size
        self.mime = mime
        self.hash = hash
        self.chunks = chunks

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let id: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let name: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let size: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let mime: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let hash: ASN1OctetString? = try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))
            let chunks: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)

            return CHAT_FileOffer(id: id, name: name, size: size, mime: mime, hash: hash, chunks: chunks)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(id)
            try coder.serialize(name)
            try coder.serialize(size)
            try coder.serialize(mime)
            if let hash = self.hash { try coder.serializeOptionalImplicitlyTagged(hash, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) }
            try coder.serialize(chunks)

        }
    }
}
