// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct PKCS_10_CertificationRequestInfo: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var version: PKCS_10_CertificationRequestInfo_version_IntEnum
    @usableFromInline var subject: InformationFramework_Name
    @usableFromInline var subjectPKInfo: AuthenticationFramework_SubjectPublicKeyInfo
    @usableFromInline var attributes: PKCS_10_Attributes
    @inlinable init(version: PKCS_10_CertificationRequestInfo_version_IntEnum, subject: InformationFramework_Name, subjectPKInfo: AuthenticationFramework_SubjectPublicKeyInfo, attributes: PKCS_10_Attributes) {
        self.version = version
        self.subject = subject
        self.subjectPKInfo = subjectPKInfo
        self.attributes = attributes

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let versionVal = try Int(derEncoded: &nodes)
            let version = PKCS_10_CertificationRequestInfo_version_IntEnum(rawValue: versionVal)
            let subject: InformationFramework_Name = try InformationFramework_Name(derEncoded: &nodes)
            let subjectPKInfo: AuthenticationFramework_SubjectPublicKeyInfo = try AuthenticationFramework_SubjectPublicKeyInfo(derEncoded: &nodes)
            let attributes: PKCS_10_Attributes = (try DER.optionalImplicitlyTagged(&nodes, tag: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)))!

            return PKCS_10_CertificationRequestInfo(version: version, subject: subject, subjectPKInfo: subjectPKInfo, attributes: attributes)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try version.serialize(into: &coder, withIdentifier: .integer)
            try coder.serialize(subject)
            try coder.serialize(subjectPKInfo)
            try coder.serializeOptionalImplicitlyTagged(attributes, withIdentifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific))

        }
    }
}
