// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias SelectedAttributeTypes_ZONAL_MATCHING = InformationFramework_MAPPING_BASED_MATCHING
