// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline indirect enum SelectedAttributeTypes_SubstringAssertion_Element: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .enumerated }
        case initial(SelectedAttributeTypes_DirectoryString)
    case any(SelectedAttributeTypes_DirectoryString)
    case `final`(SelectedAttributeTypes_DirectoryString)
    case control(PKIX1Explicit88_Attribute)
    @inlinable init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        switch rootNode.identifier {
        case ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific):
            guard case .constructed(let nodes) = rootNode.content, var iterator = Optional(nodes.makeIterator()), let inner = iterator.next() else { throw ASN1Error.invalidASN1Object(reason: "Invalid explicit tag content") }
            self = .initial(try SelectedAttributeTypes_DirectoryString(derEncoded: inner))
        case ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific):
            guard case .constructed(let nodes) = rootNode.content, var iterator = Optional(nodes.makeIterator()), let inner = iterator.next() else { throw ASN1Error.invalidASN1Object(reason: "Invalid explicit tag content") }
            self = .any(try SelectedAttributeTypes_DirectoryString(derEncoded: inner))
        case ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific):
            guard case .constructed(let nodes) = rootNode.content, var iterator = Optional(nodes.makeIterator()), let inner = iterator.next() else { throw ASN1Error.invalidASN1Object(reason: "Invalid explicit tag content") }
            self = .`final`(try SelectedAttributeTypes_DirectoryString(derEncoded: inner))
        case PKIX1Explicit88_Attribute.defaultIdentifier:
            self = .control(try PKIX1Explicit88_Attribute(derEncoded: rootNode, withIdentifier: rootNode.identifier))
            default: throw ASN1Error.unexpectedFieldType(rootNode.identifier)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        switch self {
        case .initial(let initial): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 0, tagClass: .contextSpecific)) { coder in try initial.serialize(into: &coder) }
        case .any(let any): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 1, tagClass: .contextSpecific)) { coder in try any.serialize(into: &coder) }
        case .`final`(let `final`): try coder.appendConstructedNode(identifier: ASN1Identifier(tagWithNumber: 2, tagClass: .contextSpecific)) { coder in try `final`.serialize(into: &coder) }
        case .control(let control):
                        if identifier != Self.defaultIdentifier {
                            try coder.appendConstructedNode(identifier: identifier) { coder in
                                try coder.serialize(control)
                            }
                        } else {
                            try coder.serialize(control)
                        }

        }
    }

}
