// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct AuthenticationFramework_Extension: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var extnId: ASN1ObjectIdentifier
    @usableFromInline var critical: Bool
    @usableFromInline var extnValue: ASN1OctetString

    @inlinable init(extnId: ASN1ObjectIdentifier, critical: Bool = false, extnValue: ASN1OctetString) {
        self.extnId = extnId
        self.critical = critical
        self.extnValue = extnValue
    }

    @inlinable init(derEncoded root: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let extnId = try ASN1ObjectIdentifier(derEncoded: &nodes)

            // critical is OPTIONAL with DEFAULT FALSE
            var critical: Bool = false
            var peekNodes = nodes
            if let nextNode = peekNodes.next(), nextNode.identifier == .boolean {
                critical = try Bool(derEncoded: &nodes)
            }

            let extnValue = try ASN1OctetString(derEncoded: &nodes)

            return AuthenticationFramework_Extension(extnId: extnId, critical: critical, extnValue: extnValue)
        }
    }

    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(extnId)
            // Only serialize critical if it's true (per DER rules for DEFAULT FALSE)
            if critical {
                try coder.serialize(critical)
            }
            try coder.serialize(extnValue)
        }
    }
}
