// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct AuthenticationFramework_IssuerSerial: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var issuer: PKIX1Implicit88_GeneralNames
    @usableFromInline var serial: ArraySlice<UInt8>
    @usableFromInline var issuerUID: SelectedAttributeTypes_UniqueIdentifier?
    @inlinable init(issuer: PKIX1Implicit88_GeneralNames, serial: ArraySlice<UInt8>, issuerUID: SelectedAttributeTypes_UniqueIdentifier?) {
        self.issuer = issuer
        self.serial = serial
        self.issuerUID = issuerUID

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let issuer: PKIX1Implicit88_GeneralNames = try PKIX1Implicit88_GeneralNames(derEncoded: &nodes)
            let serial: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            var issuerUID: SelectedAttributeTypes_UniqueIdentifier? = nil
var peek_issuerUID = nodes
if let next = peek_issuerUID.next(), next.identifier == SelectedAttributeTypes_UniqueIdentifier.defaultIdentifier {
    issuerUID = try SelectedAttributeTypes_UniqueIdentifier(derEncoded: &nodes)
}

            return AuthenticationFramework_IssuerSerial(issuer: issuer, serial: serial, issuerUID: issuerUID)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(issuer)
            try coder.serialize(serial)
            if let issuerUID = self.issuerUID { try coder.serialize(issuerUID) }

        }
    }
}
