// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias AuthenticationFramework_AttributeCertificate_toBeSigned = AuthenticationFramework_AttributeCertificateInfo
