// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct AuthenticationFramework_CertificateList_toBeSigned_revokedCertificates_Sequence: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var userCertificate: ArraySlice<UInt8>
    @usableFromInline var revocationDate: AuthenticationFramework_Time
    @usableFromInline var crlEntryExtensions: AuthenticationFramework_Extensions?
    @inlinable init(userCertificate: ArraySlice<UInt8>, revocationDate: AuthenticationFramework_Time, crlEntryExtensions: AuthenticationFramework_Extensions?) {
        self.userCertificate = userCertificate
        self.revocationDate = revocationDate
        self.crlEntryExtensions = crlEntryExtensions

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let userCertificate: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let revocationDate: AuthenticationFramework_Time = try AuthenticationFramework_Time(derEncoded: &nodes)
            var crlEntryExtensions: AuthenticationFramework_Extensions? = nil
var peek_crlEntryExtensions = nodes
if let next = peek_crlEntryExtensions.next(), next.identifier == AuthenticationFramework_Extensions.defaultIdentifier {
    crlEntryExtensions = try AuthenticationFramework_Extensions(derEncoded: &nodes)
}

            return AuthenticationFramework_CertificateList_toBeSigned_revokedCertificates_Sequence(userCertificate: userCertificate, revocationDate: revocationDate, crlEntryExtensions: crlEntryExtensions)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(userCertificate)
            try coder.serialize(revocationDate)
            if let crlEntryExtensions = self.crlEntryExtensions { try coder.serialize(crlEntryExtensions) }

        }
    }
}
