// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct CertificateExtensions_CertificateExactAssertion: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var serialNumber: ArraySlice<UInt8>
    @usableFromInline var issuer: InformationFramework_Name
    @inlinable init(serialNumber: ArraySlice<UInt8>, issuer: InformationFramework_Name) {
        self.serialNumber = serialNumber
        self.issuer = issuer

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let serialNumber: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let issuer: InformationFramework_Name = try InformationFramework_Name(derEncoded: &nodes)

            return CertificateExtensions_CertificateExactAssertion(serialNumber: serialNumber, issuer: issuer)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(serialNumber)
            try coder.serialize(issuer)

        }
    }
}
