// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct CHAT_CHATMessage: DERImplicitlyTaggable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var no: ArraySlice<UInt8>
    @usableFromInline var uuid: ASN1OctetString
    @usableFromInline var headers: [ASN1OctetString]
    @usableFromInline var body: CHAT_CHATProtocol
    @inlinable init(no: ArraySlice<UInt8>, uuid: ASN1OctetString, headers: [ASN1OctetString], body: CHAT_CHATProtocol) {
        self.no = no
        self.uuid = uuid
        self.headers = headers
        self.body = body

    }
    @inlinable init(derEncoded root: ASN1Node,
        withIdentifier identifier: ASN1Identifier) throws {
        self = try DER.sequence(root, identifier: identifier) { nodes in
            let no: ArraySlice<UInt8> = try ArraySlice<UInt8>(derEncoded: &nodes)
            let uuid: ASN1OctetString = try ASN1OctetString(derEncoded: &nodes)
            let headers: [ASN1OctetString] = try DER.sequence(of: ASN1OctetString.self, identifier: .sequence, nodes: &nodes)
            let body: CHAT_CHATProtocol = try CHAT_CHATProtocol(derEncoded: &nodes)

            return CHAT_CHATMessage(no: no, uuid: uuid, headers: headers, body: body)
        }
    }
    @inlinable func serialize(into coder: inout DER.Serializer,
        withIdentifier identifier: ASN1Identifier) throws {
        try coder.appendConstructedNode(identifier: identifier) { coder in
            try coder.serialize(no)
            try coder.serialize(uuid)
            try coder.serializeSequenceOf(headers)
            try coder.serialize(body)

        }
    }
}
