// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias CryptographicMessageSyntax_2010_SignatureAlgorithmIdentifier = CryptographicMessageSyntax_2010_AlgorithmIdentifier
