// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias CryptographicMessageSyntaxAlgorithms_2009_PBKDF2_PRFsAlgorithmIdentifier = CryptographicMessageSyntax_2010_AlgorithmIdentifier
