// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline typealias CryptographicMessageSyntax_2010_AlgorithmInformation_2009_AlgorithmIdentifier = AuthenticationFramework_AlgorithmIdentifier
