// Generated by ASN1.ERP.UNO Compiler, Copyright © 2023—2024 Namdak Tönpa.
import Foundation

@usableFromInline struct SelectedAttributeTypes_CaseIgnoreListMatch: DERImplicitlyTaggable, DERParseable, DERSerializable, Sendable {
    @inlinable static var defaultIdentifier: ASN1Identifier { .sequence }
    @usableFromInline var value: [SelectedAttributeTypes_DirectoryString]
    @inlinable public init(_ value: [SelectedAttributeTypes_DirectoryString]) { self.value = value }
    @inlinable public init(derEncoded rootNode: ASN1Node, withIdentifier identifier: ASN1Identifier) throws {
        self.value = try DER.sequence(of: SelectedAttributeTypes_DirectoryString.self, identifier: identifier, rootNode: rootNode)
    }
    @inlinable func serialize(into coder: inout DER.Serializer, withIdentifier identifier: ASN1Identifier) throws {
        try coder.serializeSequenceOf(value, identifier: identifier)
    }
}
